---
- name: 'install gpg'
  become: true
  apt:
    name:
    - gnupg
    update_cache: yes
  when: ansible_os_family == 'Debian'

- include_tasks: docker-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  tags:
    - docker

- include_tasks: docker-debian.yml
  when: ansible_distribution == 'Debian'
  tags:
    - docker


- name: "install {{ docker_package }}"
  become: yes
  apt:
    name: "{{ docker_package }}"
    state: present
  when: ansible_os_family == 'Debian'
  tags:
    - docker

- name: add /etc/docker/daemon.json config
  become: yes
  copy:
    src: files/docker.daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    mode: 0644

- name: 'start docker'
  become: yes
  service:
    name: docker
    enabled: yes
    state: started

- name: 'register docker'
  set_fact:
    docker_installed: true
