- name: Add Docker key [ubuntu]
  apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: docker repo [ubuntu] {{architecture}}
  apt_repository:
    repo: "deb [arch={{architecture}}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'
