---
# tasks file for fan-ansible
- name: 'include vars from {{ ansible_os_family }}.yml'
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - docker

- include: packages.yml
  become: true

- name: 'default keys'
  set_fact: pubkey_list='{{ lookup("file", item) }}'
  register: pubkeys
  with_items: '{{ authorized_keys }}'
  tags:
    - ssh_keys

- name: 'collect existing public keys'
  set_fact: pubkey_string="{{ pubkeys.results | map(attribute='ansible_facts.pubkey_list') | join('\n') }}"
  tags:
    - ssh_keys

- name: 'setup default authorized keys'
  authorized_key: user='{{ user }}' key='{{ pubkey_string }}' exclusive=true
  tags:
    - ssh_keys

- name: 'setup extra authorized keys'
  authorized_key: user='{{ user }}' key='{{ lookup("file", item) }}'
  with_items: '{{ extra_authorized_keys }}'
  tags:
    - ssh_keys

- name: 'copy gitconfig'
  copy:
    src: 'files/gitconfig'
    dest: '{{ home }}/.gitconfig'
    owner: '{{ user }}'


- include: hetzner.yml
  when: is_hetzner

- name: 'create {{ home }}/.docker dir'
  file:
    path: '{{ home }}/.docker'
    state: directory
    owner: '{{ user }}'

- include: zsh.yml

- name: add dots
  copy:
    src: "files/{{ item }}"
    dest: "{{ home }}/.{{ item }}"
    owner: '{{ user }}'
  with_items:
    - screenrc
    - bash_profile

- name: checkout .emacs.d
  git:
    repo: 'https://github.com/cybergrind/emacs_config.git'
    dest: '{{ home }}/.emacs.d'
    accept_hostkey: yes
    force: true


- include: docker.yml
  when: install_docker
  tags:
    - docker

- name: 'add user {{ user }} to docker group'
  become: yes
  user:
    name: '{{ user }}'
    groups: docker
    append: yes
  when: has_docker
