- name: 'install packages'
  package:
    name: '{{item}}'
  become: true
  tags:
    - packages
  with_items:
    - git
    - zsh
    - vim-nox
    - emacs-nox
    - screen
    - htop
    - awscli
    - fd-find
    - silversearcher-ag
    - net-tools

- name: "install ubuntu deps"
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'build-essential','libssl-dev', 'libffi-dev']
    state: present
  when: ansible_distribution == 'Ubuntu'


- name: 'install py3y packages'
  package:
    name: '{{item}}'
  become: true
  with_items:
    - python3-dev
    - python3-venv
    - python3-pip

  when:
    - ansible_distribution in ['Ubuntu', 'Debian']


- name: 'install pip'
  become: yes
  package: name='{{ pip_package }}' state=present
