- name: "install ubuntu deps"
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - build-essential
      - libssl-dev
      - libffi-dev
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: 'install packages'
  package:
    name:
    - emacs-nox
    - git
    - htop
    - httpie
    - net-tools
    - screen
    - silversearcher-ag
    - vim-nox
    - zsh
    - fd-find
    - tree
    - jq
    - docker-compose
  become: true
  tags:
    - packages

- name: 'install awscli'
  package:
    name: awscli
    state: present
  become: true
  tags:
    - packages
  when:
    - ansible_distribution_major_version < '24' or ansible_distribution == 'Debian'

- name: 'install awscli'
  snap:
    name:
     - aws-cli
    classic: true
  become: true
  tags:
    - packages
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version >= '24'

- name: 'install py3y packages'
  package:
    name:
    - python3-dev
    - python3-venv
    - python3-pip
  become: true
  when:
    - ansible_distribution in ['Ubuntu', 'Debian']
