- name: "install ubuntu deps"
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - build-essential
      - libssl-dev
      - libffi-dev
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: 'install packages'
  package:
    name: '{{ item }}'
  become: true
  failed_when: false
  tags:
    - packages
  with_items:
    - awscli
    - emacs-nox
    - git
    - htop
    - httpie
    - net-tools
    - screen
    - silversearcher-ag
    - vim-nox
    - zsh
    - fd-find
    - tree
    - jq

- name: 'install py3y packages'
  package:
    name: '{{ item }}'
  become: true
  with_items:
    - python3-dev
    - python3-venv
    - python3-pip

  when:
    - ansible_distribution in ['Ubuntu', 'Debian']
