- name: checkout oh-my-zsh
  git:
    repo: 'https://github.com/robbyrussell/oh-my-zsh.git'
    dest: '{{ home }}/.oh-my-zsh'
    accept_hostkey: yes
    version: 'master'

- name: add .zshrc
  copy:
    src: files/zshrc
    dest: '{{ home }}/.zshrc'
    owner: '{{ user }}'
    mode: '0755'

- name: add vimrc
  copy:
    src: files/vimrc
    dest: '{{ home }}/.vimrc'
    owner: '{{ user }}'
    mode: '0755'

- name: add .zshenv
  copy:
    src: files/zshenv
    dest: '{{ home }}/.zshenv'
    owner: '{{ user }}'
    mode: '0755'

- name: 'create {{ home }}/.config'
  file:
    path: '{{ home }}/.config'
    state: directory
    owner: '{{ user }}'
    mode: '0755'
  tags:
    - user_configs

- name: 'create local config in {{ home }}/.config/{{ inventory_hostname }}.sh'
  copy:
    src: 'files/configs/{{ inventory_hostname }}.sh'
    dest: '{{ home }}/.config/{{ inventory_hostname }}.sh'
    owner: '{{ user }}'
    mode: '0755'
  with_fileglob: 'files/configs/{{ inventory_hostname }}.sh'
  failed_when: false
  tags:
    - user_configs

- name: 'create {{ home }}/.config/environment.sh'
  template:
    src: 'templates/environment.sh'
    dest: '{{ home }}/.config/environment.sh'
    owner: '{{ user }}'
    mode: '0755'
  tags:
    - user_configs

- name: setup zsh as a default shell
  user: name={{ user }} shell=/usr/bin/zsh
  become: true
