- name: checkout oh-my-zsh
  git:
    repo: 'https://github.com/robbyrussell/oh-my-zsh.git'
    dest: '{{ home }}/.oh-my-zsh'
    accept_hostkey: yes

- name: add .zshrc
  copy:
    src: files/zshrc
    dest: '{{ home }}/.zshrc'
    owner: '{{ user }}'

- name: add .zshenv
  copy:
    src: files/zshenv
    dest: '{{ home }}/.zshenv'
    owner: '{{ user }}'

- file:
    path: '{{ home }}/.config'
    state: directory
    owner: '{{ user }}'

- copy:
    src: 'files/configs/{{ inventory_hostname }}.sh'
    dest: '{{ home }}/.config/{{ inventory_hostname }}.sh'
    owner: '{{ user }}'
  ignore_errors: true
  tags:
    - user_configs

- template:
    src: 'templates/environment.sh'
    dest: '{{ home }}/.config/environment.sh'
    owner: '{{ user }}'
  tags:
    - user_configs

- name: setup zsh as a default shell
  user: name={{ user }} shell=/usr/bin/zsh
  become: true
