# tramp fix
if [[ $TERM == "dumb" ]]; then
    unsetopt zle
    unsetopt prompt_cr
    unsetopt prompt_subst
    unfunction precmd
    unfunction preexec
    PS1='$ '
    return
fi


# ITERM fix
if [ ! -z "$Apple_PubSub_Socket_Render" ]; then
    declare -x PATH="/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
fi


# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ZSH_THEME="tonotdo"
# ZSH_THEME="random"
ZSH_THEME="jonathan"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git ssh-agent fabric python postgres rsync extract docker golang pip sudo systemd z)

source $ZSH/oh-my-zsh.sh

export HISTSIZE=9999999

export PYTHONPATH=.
export EDITOR='emacsclient --alternate-editor="" -nw -c'

alias em='emacs -nw'

alias aenv='. ./venv/bin/activate || . ./bin/activate'


if [ -f /usr/share/nvm/init-nvm.sh ]; then
   source /usr/share/nvm/init-nvm.sh
fi

function jobskill {
    kill -9 `jobs -p | awk '{print $3}'`
}

alias lsg='ls -lah | grep -i $1'

function mk_ssh_screen {
    ssh -t $1 "/usr/bin/screen -D -RR " $2
}

function mk_ssh_screen_pf {
    ssh -L $3 -t $1 "/usr/bin/screen -D -RR " $2
}
function pid_kill_rm_nohup {
    pid_kill $%
    rm nohup.out
}
function rmpyc {
    find . -name \*.pyc -exec rm {} \;
}

function rmtmp {
    find . -name \*.pyc -delete
    find . -name \*~ -delete
    find . -name "\#*" -delete
    find . -iname '__pycache__' -type d | xargs rm -rf
    true
}

function do_tgz {
    rm $1; tar --exclude-vcs -czf $1 *
}

function h {
    case $# in
        0)
            history;;
        1)
            history | grep $1;;
        2)
            IFS=$'\n';
            _arr=( $(history | grep $1 | cut -f 4- -d ' ') );
            _num=${_arr[$2]};
            eval $_num;;
    esac;
}

function findi {
    case $# in
        0)
            find;;
        1)
            find . -iname "*$1*";;
        2)
            find $1 -iname "*$2*";;
    esac;
}


alias pk="pid_kill_rm_nohup"
alias new_screen="screen -c ~/.screenrc2 $@"
alias e='emacsclient --alternate-editor="" -nw -c "$@"'

# Customize to your needs...
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function

if [[ "$TERM" == "dumb" ]]
then
  unsetopt zle
  unsetopt prompt_cr
  unsetopt prompt_subst
  unfunction precmd
  unfunction preexec
  PS1='$ '
fi
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

function active-window-id {
if [ ! -n "$SSH_CLIENT" ] || [ ! -n "$SSH_TTY" ]; then
echo `xprop -root | awk '/_NET_ACTIVE_WINDOW\(WINDOW\)/{print $NF}'`
fi
}


export TERM=xterm-256color

# pip zsh completion start
function _pip_completion {
  local words cword
  read -Ac words
  read -cn cword
  reply=( $( COMP_WORDS="$words[*]" \
             COMP_CWORD=$(( cword-1 )) \
             PIP_AUTO_COMPLETE=1 $words[1] ) )
}
compctl -K _pip_completion pip
# pip zsh completion end


export PATH="$HOME/.local/bin:$PATH"
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

function dck_tmp {
    docker run --rm=true $3 $4 $5 $6 -it $1 $2
}

function dck_bash_tmp {
    docker run  $2 $3 $4 $5 $6 --rm=true -it $1 /bin/bash
}


# docker exec autocompletion
function _de_completion {
    containers=( $(docker ps | awk 'NR>1{print $NF}') )
    reply=( $containers )
}
function de {
    case $# in
        0)
            if [[ $# = 0 && ! -z "$DE_DEFAULT" ]]; then
                docker exec -it -e LINES=$(tput lines) -e COLUMNS=$(tput cols) $DE_DEFAULT /bin/bash
            else
                echo 'define $DE_DEFAULT variable to use without parameters'
            fi;;
        1)
            docker exec -it -e LINES=$(tput lines) -e COLUMNS=$(tput cols) $1 /bin/bash;;
        *)
            docker exec -it -e LINES=$(tput lines) -e COLUMNS=$(tput cols) $@ ;;
    esac
}
compctl -K _de_completion de

function dck {
    docker $@
}
compctl -K _de_completion dck
# docker exec completion end


function tcp_ports {
    sudo lsof -i -n -P | grep TCP
}


function _exists {
    whence $1 > /dev/null
}

if _exists fdfind; then
   alias fd=fdfind
fi

function aws_setup {
    if [[ $AWS_READY == 1 ]]; then
        return 0
    fi
    if [[ -f ~/.keys/env ]]; then
        source ~/.keys/env
    else
        echo 'There is no env files'
        return 1
    fi

    if _exists awless; then
        source <(awless completion zsh)
    fi
    export AWS_READY=1
}

function awless_instances {
    prev=$(awless config get region)
    echo 'Region: ' $1
    awless config set region $1
    awless list instances
    awless config set region $prev
}

function aws_status {
    aws_setup
    awless_instances us-east-1
    awless_instances eu-central-1
}

# C-u to kill line from cursor to beginning
bindkey \^U backward-kill-line


export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -f -g ""'
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

if [ -f /usr/share/nvm/nvm.sh ]; then
    [ -z "$NVM_DIR" ] && export NVM_DIR="$HOME/.nvm"
    source /usr/share/nvm/nvm.sh
    source /usr/share/nvm/bash_completion
    source /usr/share/nvm/install-nvm-exec
fi

CUSTOM_CONFIG="$HOME/.config/$(hostname).sh"
[ -f "$CUSTOM_CONFIG" ] && source "$CUSTOM_CONFIG" || echo 'no custom config'

ENV_CONFIG="$HOME/.config/environment.sh"
[ -f "$ENV_CONFIG" ] && source "$ENV_CONFIG"
